load("//build_defs:defaults.bzl", "ANGULAR_CORE_DEPS", "ts_library")

package(
    default_visibility = ["//build_defs:mesop_internal"],
)

ts_library(
    name = "safe_iframe",
    srcs = glob([
        "*.ts",
    ]),
    deps = ANGULAR_CORE_DEPS,
)
