package(
    default_visibility = ["//:optic_internal"],
)

py_library(
    name = "components",
    srcs = glob(["*.py"]),
    deps = [
        "//optic/component_helpers",
        "//optic/components/button:py",
        "//protos:ui_py_proto",
    ],
)
