package(
    default_visibility = ["//:optic_internal"],
)

py_library(
    name = "component_helpers",
    srcs = glob(["*.py"]),
    deps = [
        "//optic/runtime",
        "//protos:ui_py_proto",
    ],
)
