package(
    default_visibility = ["//:optic_internal"],
)

py_library(
    name = "event_handler",
    srcs = glob(["*.py"]),
    deps = [
        "//optic/component_helpers",
        "//optic/events",
        "//optic/runtime",
        "//protos:ui_py_pb2",
    ],
)
