load("//build_defs:defaults.bzl", "ts_library")

package(
    default_visibility = ["//build_defs:mesop_internal"],
)

ts_library(
    name = "utils",
    srcs = glob(["*.ts"]),
    deps = ["//mesop/protos:ui_jspb_proto"],
)
