load("//build_defs:defaults.bzl", "py_library")

package(
    default_visibility = ["//build_defs:mesop_internal"],
)

py_library(
    name = "labs",
    srcs = glob(["*.py"]),
    deps = [
        "//mesop",
    ],
)
