load("//mesop/components:defs.bzl", "mesop_component")

package(
    default_visibility = ["//build_defs:mesop_internal"],
)

mesop_component(
    name = "html",
    ng_deps = [
        "//mesop/web/src/safe_iframe",
    ],
)
