package(
    default_visibility = ["//build_defs:optic_internal"],
)

py_library(
    name = "index",
    srcs = ["index.py"],
    deps = [
        # REF(//scripts/gen_component.py):insert_component_e2e_import
        "//optic/components/text_input/e2e",
        "//optic/components/box/e2e",
        "//optic/components/text/e2e",
        "//optic/examples",
    ],
)
