package(
    default_visibility = ["//:optic_internal"],
)

py_library(
    name = "index",
    srcs = ["index.py"],
    deps = [
        "//optic/components/text/e2e",
        "//optic/examples",
    ],
)
