# How to run:
#
# From the ai/ working directory.
#
# 1. Create dataset
# $ firectl create dataset mesop-udiff-2024-09-12 data/golden_datasets/udiff-2024-09-12.jsonl
#
# 2. Create fine-tuning job
# $ firectl create fine-tuning-job --settings-file fireworks-settings.yaml --display-name "mesop-ft-2024-09-12" --wandb-entity mesop --wandb-project mesop-ft --wandb-api-key $WANDB_API_KEY --epochs 3

dataset: mesop-dataset-08-27-2024

conversation: {}

base_model: accounts/fireworks/models/llama-v3p1-70b-instruct
