# How to run:
# $ firectl create fine-tuning-job --settings-file fireworks-settings.yaml --display-name "mesop-finetune-v2" --wandb-entity mesop --wandb-project mesop-ft --wandb-api-key $WANDB_API_KEY --epochs 3

dataset: mesop-dataset-08-27-2024

conversation: {}

base_model: accounts/fireworks/models/llama-v3p1-70b-instruct
