load("//mesop/components:defs.bzl", "mesop_component")

package(
    default_visibility = ["//build_defs:mesop_internal"],
)

mesop_component(
    name = "checkbox",
    py_deps = ["//mesop/components/text:py"],
)
