package(
    default_visibility = ["//:optic_internal"],
)

py_library(
    name = "runtime",
    srcs = glob(["*.py"]),
    deps = [
        "//optic/exceptions",
        "//optic/interactivity",
        "//protos:ui_py_proto",
    ],
)
