load("//build_defs:defaults.bzl", "py_library")

package(
    default_visibility = ["//build_defs:mesop_examples"],
)

py_library(
    name = "chat_pad_components",
    srcs = glob(["*.py"]),
    deps = [
        "//mesop",
        "//mesop/labs",
    ],
)
