load("//mesop/components:defs.bzl", "mesop_component")

package(
    default_visibility = ["//build_defs:mesop_internal"],
)

mesop_component(
    name = "sidenav",
    ng_deps = ["//mesop/web/src/utils"],
)
